---
title: "Assignment 1: Introduction"
author: Jack Eynon
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I've had some experience with data analytics using Excel and, to a lesser degree, STATA. My first exposure to R was in ENV 710, and I've since used it more for my assistantship (synthesizing NOAA commercial fishery landings data).

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident about how patient I am with troubleshooting and how I have a good foundation in quantitative skills.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about my lack of understanding of computer science and how to resolve technical issues.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/je138/Environmental_Data_Analytics_2020.git


