---
title: "Assignment 9: Spatial Analysis"
author: "Jack Eynon"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

## OVERVIEW

This exercise accompanies the lessons in Environmental Data Analytics on spatial analysis. 

## Directions
1. Use this document to create code for a map. You will **NOT** be turning in the knitted Rmd file this time, only the pdf output for a map.
2. When you have produced your output, submit **only** the pdf file for the map, without any code. Please name your file "StudentName_A09_Spatial.pdf".

The completed exercise is due on Thursday, March 19 at 1:00 pm.

## Create a map

You have three options for this assignment, and you will turn in just **one** final product. Feel free to choose the option that will be most beneficial to you. For all options, to earn full points you should use best practices for data visualization that we have covered in previous assignments (e.g., relabeling axes and legends, choosing non-default color palettes, etc.).

Here are your three options: 

1. Reproduce figure 1b from the spatial lesson, found in section 3.2.2. You may choose a state other than North Carolina, but your map should still contain the spatial features contained in figure 1b in the "img" folder. 

2. Create a new map that mixes spatial and tabular data, as in section 3.3 of the spatial lesson. You may use the maps created in the lesson as an example, but your map should contain data other than precipitation days per year. This map should include: 

* State boundary layer
* Basin boundary layer
* Gage layer
* Tabular data (as an aesthetic for one of the layers)

```{r}
fl_state_bounds_geom <- southeast_state_bounds %>%
  filter(NAME == "Florida") %>%
  st_geometry()

fl_gages <- gages %>% st_intersection(fl_state_bounds_geom)

fl_gages_climate <- fl_gages %>% left_join(my_tabular_data_raw, by = "STAID")

fl_basins_nf_seplains <- basins_nf_seplains %>%
  st_intersection(fl_state_bounds_geom)

fl_bbox <- fl_state_bounds_geom %>%
  st_buffer(dist = 150000) %>% # this value is very arbitrary just wanting to make a large buffer around geometry
  st_transform(4326) %>% # WGS84 (for lat and long)
  st_bbox()

fl_bbox_fix <- c(left = fl_bbox[[1]], bottom = fl_bbox[[2]], right = fl_bbox[[3]], top = fl_bbox[[4]])

fl_basemap <- get_map(fl_bbox_fix, maptype = 'terrain-background', source = 'stamen', zoom = 8)
st_crs(fl_basemap)

fl_state_bounds_geom_wsg84 <- fl_state_bounds_geom %>%
  st_transform(4326)

fl_basins_nf_seplains_wsg84 <- fl_basins_nf_seplains %>% st_transform(4326)

fl_gages_climate_wsg84 <- fl_gages_climate %>% st_transform(4326)

pdf(here("outputs", "basemap.test.pdf"), width = 11, height = 8.5)
ggmap(fl_basemap) +
  geom_sf(data = fl_state_bounds_geom_wsg84, fill = "lightgray") +
  geom_sf(data = fl_basins_nf_seplains_wsg84, fill = "pink", alpha = 0.3) +
  labs(title = "Florida Watersheds and Average Humidity at Gage Sites") +
  geom_sf(fl_gages_climate_wsg84, mapping = aes(color = RH_SITE), size = 2) +
  scale_color_gradient(low = "white", high = "blue") +
  labs(color = "Site average relative humidity (percent) over 30 years (1961-1990)") +
  theme_bw()
dev.off()

pdf(here("outputs", "Eynon_A09_Spatial.pdf"), width = 11, height = 8.5)
ggplot() +
  geom_sf(data = fl_state_bounds_geom, fill = "lightgray") +
  geom_sf(data = fl_basins_nf_seplains, fill = "pink", alpha = 0.3) +
  labs(title = "Florida Watersheds and Average Humidity at Gage Sites") +
  geom_sf(fl_gages_climate, mapping = aes(color = RH_SITE), size = 2) +
  scale_color_gradient(low = "white", high = "blue") +
  labs(color = "Site average relative humidity (percent) over 30 years (1961-1990)") +
  theme_bw()
dev.off()
  
```


3. Create a map of any other spatial data. This could be data from the spatial lesson, data from our other course datasets (e.g., the Litter dataset includes latitude and longitude of trap sites), or another dataset of your choosing.  Your map should include: 

* One or more layers with polygon features (e.g., country boundaries, watersheds)
* One or more layers with point and/or line features (e.g., sampling sites, roads)
* Tabular data that correpond to one of the layers, specified as an aesthetic (e.g., total litter biomass at each trap, land cover class at each trap)

Hint: One package that may come in handy here is the `maps` package, which contains several options for basemaps that cover political and geologic boundaries.
